apiVersion: tekton.dev/v1beta1
kind: Task
name: nose
spec:
  workspaces:
  - name: source
  params:
  - name: args
    description: Arguments to pass to nose (optional)
    type: string
    default: "-v"  # Run tests verbosely by default
  steps:
  - name: test
    image: python:3.9-slim  # Adjust image based on your requirements
    workingDir: $(workspaces.source.path)  # Set working directory to workspace
    script: |  # Use a multi-line string for the script
      #!/bin/bash
      set -e
      python -m pip install --upgrade pip wheel
      pip install -r requirements.txt
      nosetests $(params.args)
